kind: Service
apiVersion: v1
metadata:
  name: k8s-service
spec:
  type: NodePort
  selector:
    app: k8s
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  labels:
    app: k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s
      track: stable
  template:
    metadata:
      labels:
        app: k8s
        track: stable
    spec:
      containers:
      - name: k8s
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
